### ISSUE TITLE
The command 'bash install.sh' returned a non-zero code: 2

### ISSUE THREAD

**Issue by yangningning** [MPC-SoK/frameworks#12]
after i typed the command line: "docker build aby"  ,error occurred:
 CMake Error at /usr/share/cmake-3.12/Modules/FindBoost.cmake:2048 (message):
  Unable to find the requested Boost libraries.
  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  extern/ENCRYPTO_utils/CMakeLists.txt:24 (find_package)
OTExtension was not found: add OTExtension subdirectory
-- Configuring incomplete, errors occurred!
See also "/root/ABY/build/CMakeFiles/CMakeOutput.log".
See also "/root/ABY/build/CMakeFiles/CMakeError.log".
make: *** No targets specified and no makefile found.  Stop.
The command 'bash install.sh' returned a non-zero code: 2

how can solve it? thank you

**Comment by marsella** [comment]
Looks like ABY has updated their build structure. Will update shortly.

**Comment by yangningning** [comment]
Thank you very much for your help,Please update as soon as possible.

**Comment by marsella** [comment]
This is fixed now.
