### ISSUE TITLE
FRESCO is an end-to-end framework

### ISSUE THREAD

**Issue by GuutBoy** [MPC-SoK/frameworks#2]
This is a really cool project! Thank you so much for doing it!

However, as one of the developers of [FRESCO](https://github.com/aicis/fresco) I am a little puzzled why you would describe it as "doesn't provide an end-to-end framework itself" (https://github.com/MPC-SoK/frameworks/wiki/Projects-Not-Surveyed). 

I would say that it does, but maybe I am not understanding what you mean by end-to-end?

Anyway, if you are interested we would be happy to make a PR with the sample programs implemented in FRESCO.

**Comment by marsella** [comment]
Thanks! 

We're aiming for frameworks that include a front-end compiler (converts a high-level language or library to a circuit or other intermediate representation) and a back-end protocol implementation (consumes the circuit/IR and executes a computation) and has a relatively seamless transition between the two. My impression was that FRESCO's contribution is a set of APIs to connect front- and back-ends.

If I misunderstood the contribution of FRESCO and you include a front-end compiler, then we'd be happy to merge in a PR with the sample programs.
