### ISSUE TITLE
Output bits

### ISSUE THREAD

**Issue by nihalar** [MPC-SoK/frameworks#22]
How can I know the output bits for CBMC-GC-2? There doesn't seem to be any output file for it.

**Comment by marsella** [comment]
Which framework are you working with? Many of them print the output when you run the program.

**Comment by marsella** [comment]
Just saw your edit. CBMC-GC-2 is a circuit generator, so it doesn't actually run a secure computation. It only creates a circuit that _could_ be used by an MPC protocol that consumes boolean circuits. 

There is a simulation function that you can use to test the correctness of the circuit. Run the `geninput` script as described in the `README`. The test inputs are in `test.spec`. 

The output wires themselves are encoded in one of the circuit description files. Probably `output.gate.txt`, but I haven't parsed the new output format carefully enough to be sure.
