### ISSUE TITLE
xtabs on PICCO

### ISSUE THREAD

**Issue by schorfi** [MPC-SoK/frameworks#23]
hey,

I got a question regarding the xtabs test program.
Why are you not considering every element for bin-summing to obfuscate data correlations, as you do in xtabs on sharemind for example. The test here is only summing up, if their id matches and only sums the actual bin. I would interpret you can deduce equivalence of the ID and later somehow which bin it belongs? So, doesnt this reveal information about the input data and/or its structure? In the sharemind xtabs you do an oblivious transfer to obfuscate.
I thought, you might not consider doing this, as PICCO employs Mux for private index, but isnt this a public index here, so shouldn't apply? Any help/explanation appreciated.

some other issues I encountered while trying to make the example run (are not related to you, rather to picco):
- two dim input arrays are not two lines of input with many comma separated values; convenience issue; rather it is really first dimension = row; resulting in many lines for the xtabs example; picco-utility doesn't check or catch for violation of this dimensionality, 
even though, it could know what to expect
- further, I have observed that the created shares correlate; same input for two input-providers create same shares; So a computation node can deduce, at least, that some of the input of 1 is equal to input 2; why would you want to accept  that?

Kind regards

**Comment by marsella** [comment]
Hi,

The variable `matching_bin` on [line 30](https://github.com/MPC-SoK/frameworks/blob/master/picco/source/xtabs/xtabs.c#L30) is a private integer! PICCO has private ints by default. When the program is compiled, it gets expanded into a mux.

You're correct about the input limitations---this is basically an engineering issue. You could probably add those checks to the picco-utility if it's annoying enough for you.

I'm surprised about the share correlation (I haven't looked into it). Do you mean on multiple runs, you get the same shares for the same values (that sounds like a RNG seed issue)? Or on one run with multiple matching inputs, you get the same shares? You might want to contact Marina Blanton about it.
