### ISSUE TITLE
Issues in oblivm

### ISSUE THREAD

**Issue by MuleiOnline** [MPC-SoK/frameworks#25]
I want to run some examples in oblivm framework. However, I meet two issues:
1. when i run this command: 
`./run-compiler.sh [PORT] examples/<program>/<program>.lcc`
 it come out :
`Exception in thread "main" java.lang.NumberFormatException: For input string: "[PORT]"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.oblivm.compiler.cmd.Cmd.main(Cmd.java:68)
javac: no source files`
when i delete [PORT], it come out:
`[INFO]	Compilation finishes successfully.
javac: no source files
Usage: javac <options> <source files>`

2. when I want to run:
`./runtogether.sh examples/<program>/input_alice.txt examples/<program>/input_bob.txt`
there is no runtogether.sh file.

I am a new researcher, maybe the question is too simple, but it bother me a lot. Thanks for answer!

**Comment by marsella** [comment]
Hi Lei,

In these examples, you have to replace [PORT] with a port number (like
8888) and <program> with one of the names of the example programs. If you
want to run the mult3 example in port 8888, the actual command you type in
the terminal is:

./run-compiler.sh 8888 examples/mult3/mult3.lcc

Same issue in your second example.

**Comment by MuleiOnline** [comment]
solved， thanks~
