### ISSUE TITLE
ObliVM default mode

### ISSUE THREAD

**Issue by mkskeller** [MPC-SoK/frameworks#28]
ObliVM seems to run some circuit verification mode by default instead of actual garbled circuits when run on Linux. Should this be changed?

**Comment by mkskeller** [comment]
Condition on OS here: https://github.com/oblivm/ObliVMLang/blob/50ed0fbb556a157c0c85440dabf141a3cf7384c5/java/com/oblivm/compiler/backend/flexsc/FlexSCCodeGenerator.java#L80

Mode setting here: https://github.com/oblivm/ObliVMLang/blob/50ed0fbb556a157c0c85440dabf141a3cf7384c5/java/com/oblivm/compiler/backend/flexsc/FlexSCCodeGenerator.java#L141

**Comment by marsella** [comment]
Yeah, it looks like we don't even download the GC backend (https://github.com/oblivm/ObliVMGC). This should definitely be integrated correctly.

**Comment by mkskeller** [comment]
The backend comes in jar file, so that's actually available. I've made a pull request to do actual computation.

**Comment by marsella** [comment]
Thanks for the fix, added it and also updated the ObliVM README to explain where all these garbled circuits come from.
