### ISSUE TITLE
How to run AES.mpc?

### ISSUE THREAD

**Issue by DG66** [MPC-SoK/frameworks#30]
hey
I would like to ask how to run aes.mpc with mp-spdz in the docker？
I don't know how to choose the protocol to run AES，and the number of parties and the format of operation like the example of mult3.mpc
Maybe its a low-level question 😄
Thank you for your reply

**Comment by mkskeller** [comment]
All protocols should be able to run AES, so the choice depends on the security you want to achieve. You can read the paragraph on security models in Section 2 of https://eprint.iacr.org/2020/521.
