### ISSUE TITLE
print_ln wat not executed after run ./Player.x

### ISSUE THREAD

**Issue by wuyahuang** [MPC-SoK/frameworks#38]
Hi, I'm a beginner of SCALE-MAMBA. It looks like the innerprod.mpc is not executed after run ./Player.x

```./Player.x 0 Programs/innerprod -pnb 7000```

Output:
```
(Min,Max) number of ...
	(0,infty) multiplication triples
	(0,infty) square pairs
	(0,infty) bits
0
127.0.0.1
Player1.crt
P1
1
127.0.0.1
Player2.crt
P2


p=1073872897
sm::0:: loading certificate from Cert-Store/Player1.crt
Opening file Programs/innerprod/innerprod.sch
Number of online threads I will run in parallel =  1
Number of program sequences I need to load =  1
Loading program 0 from Programs/innerprod/innerprod-0.bc
```

The source code of innerprod.mpc:
```
sum = sint(0)
aaaas = sint.Array(10)
bbbbs = sint.Array(10)

for i in range(10):
  aaaas[i] = sint(i) # sint.get_private_input_from(0)
  bbbbs[i] = sint(i*2) # sint.get_private_input_from(1)
  

for i in range(10):
  sum = sum + (aaaas[i] * bbbbs[i])

print_ln("InnerProd: %s", sum.reveal())
```

Where is the result output from `print_ln("InnerProd: %s", sum.reveal())` ?

**Comment by wuyahuang** [comment]
It works after set -pnb to same value.

./Player.x 0 Programs/innerprod -pnb 7000
./Player.x 1 Programs/innerprod -pnb 7000
./Player.x 2 Programs/innerprod -pnb 7000

**Comment by marsella** [comment]
Glad you figured it out! In our examples you shouldn't have to specify the port at all, unless you have some special case.
