### ISSUE TITLE
SCALE-MAMBA compile failed

### ISSUE THREAD

**Issue by glowwormX** [MPC-SoK/frameworks#43]
When I run the command that `docker build -t scalemamba .`,
`make progs` in the `install.sh` script has errror: 
```
OT/exROT.cpp: In member function 'void exROT_Sender::next_iteration(Player&, unsigned int, std::vector<std::vector<gf2n> >&)':
OT/exROT.cpp:61:49: error: no matching function for call to 'ceil(unsigned int)'
   unsigned int nbBlocks= ceil(size / OT_comp_sec);
```
What is the cause of it？

**Comment by marsella** [comment]
I'm not seeing that error when I run it. Have you pulled the latest version?

What system are you running on?

**Comment by marsella** [comment]
Closing this for no response, please re-open with more details if it remains an issue.
