### ISSUE TITLE
SCALE-MAMBA docker image building issue

### ISSUE THREAD

**Issue by ding-yt** [MPC-SoK/frameworks#45]
Hi, I tried docker `build -t scalemamba . `and then start the container. However, there was no SCALE-MAMBA folder in the container. I noticed that the second line in `install.sh` file did not specify the path where should SCALE-MAMBA be cloned to:

```
# download SCALE-MAMBA v1.5
cd  
git clone https://github.com/KULeuven-COSIC/SCALE-MAMBA.git
...
```

So I changed it to 
```
# download SCALE-MAMBA v1.5
cd  ~
git clone https://github.com/KULeuven-COSIC/SCALE-MAMBA.git
...
```

Seems to fix the problem.

**Comment by marsella** [comment]
The default behavior of the `cd` command on Linux is to go to the home (`~`) directory, so these two versions should have the same behavior. I'm guessing SCALE-MAMBA failed to clone for a different reason in your case.

Either way, I'm glad it's working! Feel free to open another issue if anything else comes up.
