### ISSUE TITLE
Can't generate inputs for ABY mult3 example program

### ISSUE THREAD

**Issue by Mikerah** [MPC-SoK/frameworks#46]
I'm trying to run and play with the basic example programs for the ABY framework. I was able to successfully build the docker image and run it. However, when I run the command 
`python ~/ABY/src/examples/geninput.py -e <ex>`, I get the following error message on my bash shell `bash: syntax error near unexpected token newline`. How do I attempt to fix this?

**Comment by marsella** [comment]
You can replace `<ex>` in that command with the specific example for which you want data. For mult3, you'd run the command
```
python ~/ABY/src/examples/geninput.py -e mult3
``` 
You can see the output in the new files `mult3.0.dat` and `mult3.1.dat` in the `~/ABY/src/examples/mult3/data` directory.

You can similarly replace `mult3` with `innerprod`; I haven't written data generation for `xtabs`.
